[package]
name = "dco3"
version = "0.4.1"
edition = "2021"
authors = ["Octavio Simone"]
repository = "https://github.com/unbekanntes-pferd/dco3"
homepage = "https://github.com/unbekanntes-pferd/dco3"
license = "MIT"
readme = "README.md"
keywords = ["dracoon", "api-client", "rust-sdk"]
description = "Async API wrapper for DRACOON in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
# HTTP client
reqwest = {version = "0.11.18", features = ["json", "stream"]}
reqwest-middleware = "0.2.2"
reqwest-retry = "0.2.2"

# crypto 
dco3_crypto = "0.5.1"

# async runtime and utils
tokio = { version = "1.29.1", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["full"] }
async-trait = "0.1.72"
async-stream = "0.3.5"
futures-util = "0.3.28"
bytes = "1.4.0"

# parsing
serde = { version = "1.0.178", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.104"

# error handling
thiserror = "1.0.44"
retry-policies = "0.1.2"

# logging and tracing
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.17", features = ["env-filter"]}

# utils
url = "2.4.0"
base64 = "0.21.2"
chrono = "0.4.26"


[dev-dependencies]
mockito = "1.1.0"
tokio-test = "0.4.2"
